### ISSUE TITLE
404 Not Found: sutro-jsdoc-theme@latest

### ISSUE THREAD

**Issue by sabsaxo** [arnog/sutro-jsdoc-theme#1]
I get:

```
404 Not Found: sutro-jsdoc-theme@latest`
```
when running:

```
npm install --save-dev sutro-jsdoc-theme
```

**Comment by arnog** [comment]
The package was not published to npm. It is now.

**Comment by blaasvaer** [comment]
Well, especially if you're supposed to do:

`$ npm install --save-dev sutro-jsdoc-theme`

Thanks.
